### PR TITLE
Remove useless whitespaces

### PR DESCRIPTION
**Pull request by yaaax**
Add trim markers and convert HTML comments into Go template comments

### CODE REVIEW

**Comment by jygastaud** [comment]
Thanks @yaaax for your contribution.
At first review, it looks good to me.
I will give it a try ASAP.

**Comment by jygastaud** [comment]
@yaaax Sorry I completely forgot about that PR.
If you want to update it, I will be happy to (really) merge it.

**Comment by yaaax** [comment]
Updated !

**Comment by jygastaud** [comment]
Thanks @yaaax

**Pull request merged**
